kind = "web"
previewPath = "/"
title = "ELIENUS MUSKIUS"
version = "1.0.0"
id = "artifacts/elienus"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23278

[services.development]
run = "pnpm --filter @workspace/elienus run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/elienus", "run", "build" ]
publicDir = "artifacts/elienus/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23278"
BASE_PATH = "/"
